-- Run this in the Supabase SQL editor.
-- It creates the public dinner_options table and seeds it with the current local JSON data.

create table if not exists public.dinner_options (
  id text primary key,
  name text not null,
  category text not null,
  scene text not null check (scene in ('delivery', 'dine-in', 'both')),
  budget text not null check (budget in ('low', 'medium', 'high')),
  moods text[] not null default '{}',
  flavors text[] not null default '{}',
  group_sizes text[] not null default '{}',
  hunger_level text not null check (hunger_level in ('light', 'normal', 'very')),
  reason text not null,
  tips text not null,
  image text not null,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dinner_options enable row level security;

drop policy if exists "Public read enabled dinner options" on public.dinner_options;
create policy "Public read enabled dinner options"
  on public.dinner_options
  for select
  using (enabled = true);

insert into public.dinner_options (
  id,
  name,
  category,
  scene,
  budget,
  moods,
  flavors,
  group_sizes,
  hunger_level,
  reason,
  tips,
  image,
  enabled,
  sort_order
) values
(
  'hotpot',
  '热辣小火锅',
  '火锅',
  'dine-in',
  'high',
  ARRAY['comfort', 'social', 'spicy']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['couple', 'group']::text[],
  'very',
  '热气和蘸料能迅速把晚上的犹豫清空，特别适合多人一起吃。',
  '选鸳鸯锅，点一份蔬菜拼盘和主食，别让预算在肥牛上失控。',
  'hotpot',
  true,
  1
),
(
  'malatang',
  '自选麻辣烫',
  '麻辣烫',
  'delivery',
  'low',
  ARRAY['spicy', 'comfort', 'lazy']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['solo', 'couple']::text[],
  'very',
  '自由度高、出餐快，想吃重口味但不想认真点菜时很稳。',
  '先选蛋白和绿叶菜，再加一份粉面，汤底选微辣更不容易翻车。',
  'malatang',
  true,
  2
),
(
  'bbq',
  '夜宵烧烤拼盘',
  '烧烤',
  'both',
  'medium',
  ARRAY['social', 'spicy', 'reward']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['couple', 'group']::text[],
  'normal',
  '适合边吃边聊天，碳烤香气会让普通晚上变得像小聚会。',
  '点肉串、烤蔬菜和一份主食，外卖备注少油少盐会舒服很多。',
  'bbq',
  true,
  3
),
(
  'sushi',
  '寿司刺身便当',
  '日料',
  'both',
  'high',
  ARRAY['fresh', 'reward', 'quiet']::text[],
  ARRAY['fresh', 'light']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'normal',
  '清爽、有仪式感，不会把晚餐吃成一场战斗。',
  '很饿就搭配乌冬或茶碗蒸，单吃寿司可能后半夜想加餐。',
  'sushi',
  true,
  4
),
(
  'korean',
  '韩式拌饭炸鸡组',
  '韩餐',
  'delivery',
  'medium',
  ARRAY['reward', 'comfort', 'social']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'very',
  '拌饭负责踏实，炸鸡负责快乐，适合需要一点奖励的晚上。',
  '两个人点半份炸鸡加一份拌饭，快乐和负担都刚刚好。',
  'korean',
  true,
  5
),
(
  'noodles',
  '牛肉粉面套餐',
  '粥粉面',
  'delivery',
  'low',
  ARRAY['lazy', 'comfort', 'quiet']::text[],
  ARRAY['savory', 'light']::text[],
  ARRAY['solo']::text[],
  'normal',
  '快、暖、稳定，是不想冒险时的晚餐保险牌。',
  '加蛋或牛肉比盲目加大份更划算，汤粉外卖记得备注汤面分装。',
  'noodles',
  true,
  6
),
(
  'salad',
  '轻食能量碗',
  '轻食',
  'delivery',
  'medium',
  ARRAY['fresh', 'quiet', 'lazy']::text[],
  ARRAY['light', 'fresh']::text[],
  ARRAY['solo', 'couple']::text[],
  'light',
  '适合想吃干净一点、又不想真的做饭的夜晚。',
  '优先选鸡胸、牛肉或豆腐这类蛋白，酱汁单独放更好控制味道。',
  'salad',
  true,
  7
),
(
  'burger',
  '炸鸡汉堡套餐',
  '炸鸡汉堡',
  'delivery',
  'medium',
  ARRAY['reward', 'lazy', 'comfort']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'very',
  '不用思考、满足感强，适合今天脑力已经见底的时候。',
  '换无糖饮料或少点一份薯条，快乐不会少太多。',
  'burger',
  true,
  8
),
(
  'home-style',
  '家常炒菜盖饭',
  '家常菜',
  'both',
  'low',
  ARRAY['comfort', 'quiet', 'lazy']::text[],
  ARRAY['savory', 'light']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'normal',
  '像认真吃了一顿饭，但决策成本很低。',
  '一荤一素配米饭最稳，堂食可以看看今日例汤。',
  'home-style',
  true,
  9
),
(
  'thai',
  '泰式酸辣套餐',
  '东南亚菜',
  'both',
  'medium',
  ARRAY['fresh', 'reward', 'spicy']::text[],
  ARRAY['spicy', 'fresh', 'sweet']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '酸辣和香草味会把味觉叫醒，适合想换个频道的晚上。',
  '冬阴功、炒河粉和青木瓜沙拉三选二，就很有完成度。',
  'thai',
  true,
  10
),
(
  'congee',
  '砂锅粥小菜',
  '粥点',
  'both',
  'medium',
  ARRAY['quiet', 'comfort', 'fresh']::text[],
  ARRAY['light', 'fresh']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'light',
  '温和、不刺激，适合加班后或者胃口不太野的晚上。',
  '配蒸点和青菜，堂食比外卖口感更好。',
  'congee',
  true,
  11
),
(
  'pizza',
  '披萨分享盒',
  '披萨',
  'delivery',
  'high',
  ARRAY['social', 'reward', 'lazy']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['couple', 'group']::text[],
  'very',
  '适合多人分食，也适合边看剧边解决晚饭。',
  '选一个经典口味加一个清爽小食，比全肉披萨更耐吃。',
  'pizza',
  true,
  12
),
(
  'luosifen',
  '螺蛳粉加料碗',
  '螺蛳粉',
  'delivery',
  'low',
  ARRAY['spicy', 'reward', 'lazy']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['solo']::text[],
  'very',
  '酸辣重口味很有存在感，适合想吃点有记忆点的晚上。',
  '加腐竹和青菜就够完整，怕太冲可以备注少酸笋或另放辣油。',
  'luosifen',
  true,
  13
),
(
  'bbq-rice',
  '烤肉拌饭',
  '拌饭',
  'delivery',
  'low',
  ARRAY['comfort', 'lazy', 'spicy']::text[],
  ARRAY['savory', 'spicy']::text[],
  ARRAY['solo']::text[],
  'very',
  '肉、饭、酱一起解决，顶饿又不需要复杂选择。',
  '多加一份蔬菜或海苔碎，酱汁分装会更不腻。',
  'bbq-rice',
  true,
  14
),
(
  'charcoal-bbq',
  '炭火烤肉局',
  '烤肉',
  'dine-in',
  'high',
  ARRAY['reward', 'social', 'comfort']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['couple', 'group']::text[],
  'very',
  '适合认真吃一顿，也适合把晚餐变成小聚会。',
  '先点拼盘再补单品，配生菜和泡菜会比全程吃肉更舒服。',
  'charcoal-bbq',
  true,
  15
),
(
  'sauerkraut-fish',
  '酸菜鱼双人锅',
  '酸菜鱼',
  'both',
  'medium',
  ARRAY['fresh', 'spicy', 'social']::text[],
  ARRAY['fresh', 'spicy', 'savory']::text[],
  ARRAY['couple', 'group']::text[],
  'normal',
  '酸爽开胃，比火锅轻一点，但共享感还在。',
  '两个人选小份鱼加一份粉，外卖备注鱼片和汤分开更稳。',
  'sauerkraut-fish',
  true,
  16
),
(
  'fried-skewers',
  '炸串小食盒',
  '炸串',
  'delivery',
  'low',
  ARRAY['reward', 'lazy', 'social']::text[],
  ARRAY['savory', 'spicy']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'normal',
  '快乐来得很快，适合不想吃正餐但又想有点仪式感。',
  '荤素各半，再加一份主食或饮料，别只点淀粉串。',
  'fried-skewers',
  true,
  17
),
(
  'xinjiang-rice-noodles',
  '新疆炒米粉',
  '炒米粉',
  'delivery',
  'low',
  ARRAY['spicy', 'reward', 'comfort']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['solo', 'couple']::text[],
  'very',
  '酱香和辣度都很直接，适合很饿又想吃重口的一餐。',
  '第一次点选中辣更稳，加鸡肉或牛肉比单加米粉更满足。',
  'xinjiang-rice-noodles',
  true,
  18
),
(
  'burrito',
  '墨西哥卷饼',
  '卷饼',
  'delivery',
  'medium',
  ARRAY['fresh', 'lazy', 'reward']::text[],
  ARRAY['fresh', 'savory']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '拿起来就能吃，蔬菜、肉和酱料都在一个卷里。',
  '选鸡肉或牛肉基底，酱料少一点，外卖路上不容易塌。',
  'burrito',
  true,
  19
),
(
  'curry-omurice',
  '咖喱蛋包饭',
  '咖喱饭',
  'both',
  'medium',
  ARRAY['comfort', 'reward', 'quiet']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '软乎乎、热乎乎，适合想要一点安慰感的晚餐。',
  '选猪排或鸡排会更顶饿，咖喱酱不够可以备注多一点。',
  'curry-omurice',
  true,
  20
),
(
  'grilled-fish',
  '烤鱼小锅',
  '烤鱼',
  'dine-in',
  'high',
  ARRAY['spicy', 'social', 'reward']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['couple', 'group']::text[],
  'very',
  '有锅气、有配菜、有分享感，适合不想吃火锅但想热闹一点。',
  '两三个人点一条鱼加豆皮、土豆和青菜，主食最后再看胃口。',
  'grilled-fish',
  true,
  21
),
(
  'oden',
  '关东煮便利餐',
  '关东煮',
  'both',
  'low',
  ARRAY['comfort', 'quiet', 'lazy']::text[],
  ARRAY['light', 'savory']::text[],
  ARRAY['solo']::text[],
  'light',
  '热汤和小份量很友好，适合想轻轻吃但不想只喝粥。',
  '豆腐、萝卜、蛋白类各选一点，再配饭团会更像一餐。',
  'oden',
  true,
  22
),
(
  'sweet-tea-cake',
  '奶茶甜品轻晚餐',
  '甜品饮品',
  'delivery',
  'medium',
  ARRAY['reward', 'lazy', 'quiet']::text[],
  ARRAY['sweet', 'fresh']::text[],
  ARRAY['solo', 'couple']::text[],
  'light',
  '不算正经大餐，但很适合只想给今天一点甜头的夜晚。',
  '奶茶选半糖，再配三明治或小蛋糕，别让晚饭只剩一杯糖。',
  'sweet-tea-cake',
  true,
  23
),
(
  'roast-meat-rice',
  '粤式烧腊饭',
  '烧腊',
  'both',
  'medium',
  ARRAY['comfort', 'lazy', 'reward']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '烧鸭、叉烧和米饭的组合稳定可靠，适合想吃香一点但不想冒险。',
  '双拼比单拼更有层次，加青菜和例汤就是完整晚餐。',
  'roast-meat-rice',
  true,
  24
),
(
  'butter-chicken-rice',
  '印度黄油鸡饭',
  '印度菜',
  'both',
  'medium',
  ARRAY['comfort', 'reward', 'quiet']::text[],
  ARRAY['savory', 'sweet']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '奶香咖喱和米饭很有安慰感，适合想换个香料频道的晚上。',
  '搭配烤饼或一份蔬菜，酱汁多一点会更适合拌饭。',
  'butter-chicken-rice',
  true,
  25
),
(
  'shawarma-wrap',
  '中东沙威玛卷',
  '中东风味',
  'delivery',
  'medium',
  ARRAY['fresh', 'lazy', 'reward']::text[],
  ARRAY['fresh', 'savory']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '烤肉、蔬菜和酸奶酱包在一起，清爽但不会空虚。',
  '酱料另放更稳，想更顶饿可以加薯角或鹰嘴豆泥。',
  'shawarma-wrap',
  true,
  26
),
(
  'beef-pho',
  '越南牛肉河粉',
  '越南菜',
  'both',
  'medium',
  ARRAY['fresh', 'comfort', 'quiet']::text[],
  ARRAY['fresh', 'light']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '汤底清亮、香草提神，适合想吃热乎但不想太重的晚餐。',
  '外卖备注汤粉分装，挤点青柠会更醒胃。',
  'beef-pho',
  true,
  27
),
(
  'banh-mi',
  '越南法棍三明治',
  '越南菜',
  'delivery',
  'low',
  ARRAY['fresh', 'lazy', 'quiet']::text[],
  ARRAY['fresh', 'savory']::text[],
  ARRAY['solo']::text[],
  'light',
  '脆面包、腌菜和肉馅很利落，适合不想吃太满的一餐。',
  '选鸡肉或牛肉馅，怕晚点饿就加一杯汤或小食。',
  'banh-mi',
  true,
  28
),
(
  'greek-pita',
  '希腊烤肉皮塔',
  '地中海菜',
  'both',
  'medium',
  ARRAY['fresh', 'social', 'reward']::text[],
  ARRAY['fresh', 'savory']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '烤肉、蔬菜和酸奶酱很平衡，清爽又有满足感。',
  '配沙拉或烤蔬菜，比单点肉卷更像一顿完整晚餐。',
  'greek-pita',
  true,
  29
),
(
  'doner-rice',
  '土耳其烤肉饭',
  '土耳其菜',
  'delivery',
  'medium',
  ARRAY['comfort', 'lazy', 'reward']::text[],
  ARRAY['savory', 'spicy']::text[],
  ARRAY['solo', 'couple']::text[],
  'very',
  '烤肉和米饭的组合直接顶饿，适合不想复杂点菜的时候。',
  '加蔬菜和酸奶酱能解腻，辣酱单独放更好控。',
  'doner-rice',
  true,
  30
),
(
  'yunnan-rice-noodles',
  '云南过桥米线',
  '云南菜',
  'dine-in',
  'medium',
  ARRAY['comfort', 'fresh', 'quiet']::text[],
  ARRAY['light', 'fresh']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'normal',
  '汤、米线和小料分层上桌，温和又有一点仪式感。',
  '堂食体验更好，先下肉片再下蔬菜和米线。',
  'yunnan-rice-noodles',
  true,
  31
),
(
  'roujiamo-liangpi',
  '陕西肉夹馍凉皮组',
  '陕西小吃',
  'both',
  'low',
  ARRAY['fresh', 'comfort', 'lazy']::text[],
  ARRAY['fresh', 'savory']::text[],
  ARRAY['solo', 'couple']::text[],
  'normal',
  '一个扎实一个清爽，组合起来比单点主食更有层次。',
  '凉皮少辣多醋更开胃，肉夹馍趁热吃口感最好。',
  'roujiamo-liangpi',
  true,
  32
),
(
  'chaoshan-beef-kway-teow',
  '潮汕牛肉粿条',
  '潮汕菜',
  'dine-in',
  'medium',
  ARRAY['comfort', 'fresh', 'quiet']::text[],
  ARRAY['fresh', 'light']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'normal',
  '牛肉鲜、汤底清，适合想认真吃但不想重油重辣的时候。',
  '堂食点现切牛肉更稳，配沙茶酱但别盖过汤味。',
  'chaoshan-beef-kway-teow',
  true,
  33
),
(
  'northeast-dumplings',
  '东北饺子小菜',
  '东北菜',
  'both',
  'low',
  ARRAY['comfort', 'social', 'quiet']::text[],
  ARRAY['savory', 'light']::text[],
  ARRAY['solo', 'couple', 'group']::text[],
  'normal',
  '热饺子和小凉菜很有家常感，一个人或多人都不尴尬。',
  '点一份酸辣小菜配饺子，外卖记得要醋和蒜泥。',
  'northeast-dumplings',
  true,
  34
),
(
  'veggie-quinoa-tofu',
  '素食藜麦豆腐碗',
  '素食轻食',
  'delivery',
  'medium',
  ARRAY['fresh', 'quiet', 'lazy']::text[],
  ARRAY['fresh', 'light']::text[],
  ARRAY['solo', 'couple']::text[],
  'light',
  '有蛋白、有谷物、有蔬菜，适合想轻负担但不想只吃草。',
  '酱汁单独放，豆腐或鹰嘴豆加量会更抗饿。',
  'veggie-quinoa-tofu',
  true,
  35
),
(
  'seafood-paella',
  '西班牙海鲜饭',
  '西班牙菜',
  'dine-in',
  'high',
  ARRAY['reward', 'social', 'fresh']::text[],
  ARRAY['fresh', 'savory']::text[],
  ARRAY['couple', 'group']::text[],
  'normal',
  '海鲜和米饭很有分享感，适合把普通晚餐升级一下。',
  '两个人以上点更划算，配一份沙拉或烤蔬菜会更清爽。',
  'seafood-paella',
  true,
  36
),
(
  'roasted-fish',
  '烤鱼',
  '烤鱼',
  'dine-in',
  'high',
  ARRAY['spicy', 'social', 'reward']::text[],
  ARRAY['spicy', 'savory']::text[],
  ARRAY['couple', 'group']::text[],
  'very',
  '一整条鱼加配菜很有存在感，适合想吃热闹、重口、能分享的一顿。',
  '选香辣或蒜香口味更稳，配豆皮、土豆和青菜，主食最后再加。',
  'grilled-fish',
  true,
  37
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  scene = excluded.scene,
  budget = excluded.budget,
  moods = excluded.moods,
  flavors = excluded.flavors,
  group_sizes = excluded.group_sizes,
  hunger_level = excluded.hunger_level,
  reason = excluded.reason,
  tips = excluded.tips,
  image = excluded.image,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order,
  updated_at = now();
